# Generated by Django 4.0.5 on 2022-09-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0021_alter_jobmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubmissionmodel',
            name='drive_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productsubmissionmodel',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='submitted_file'),
        ),
    ]
